### ISSUE TITLE
Submission for assignment 1

### ISSUE THREAD

**Issue by ngxminhphuc** [ngxminhphuc/df-frontend-2023#1]
Implement with browser's local storage - Link demo: [https://df-frontend-23-1.netlify.app/](https://df-frontend-23-1.netlify.app/)

**Comment by chinhld12** [comment]
Nice works,

## Requirements

* [x]  Render correct table elements
* [x]  Create book
* [x]  Delete book
* [x]  Search book by title
* [ ]  Semantic HTML
* [x]  Standard use of CSS and JavaScript
* [x]  Store data in LocalStorage

Final result: ✅ passed

## Feedback

1. Should be a `button` element
https://github.com/ngxminhphuc/df-frontend-2023/blob/1eb943b12b6d76fb503de2b18e98d03dd83cd42f/assignment-1/index.html#L86-L100
https://github.com/ngxminhphuc/df-frontend-2023/blob/1eb943b12b6d76fb503de2b18e98d03dd83cd42f/assignment-1/index.html#L139-L153

2. Should sanitize the form input HTML before using any method to directly manipulate the HTML. Use `insertAdjacentHTML` still similar to `innerHTML` which can cause an XSS attack.
![image](https://github.com/ngxminhphuc/df-frontend-2023/assets/71743905/dfb98396-7545-444e-a7f5-8d9fdaed5839)
![image](https://github.com/ngxminhphuc/df-frontend-2023/assets/71743905/e02a5b66-d142-4a95-aa72-311b3cfd6a7d)

3. Handling `localStorage` operations should be used with error handling (`try-catch`) to prevent issues with bad JSON data.
https://github.com/ngxminhphuc/df-frontend-2023/blob/1eb943b12b6d76fb503de2b18e98d03dd83cd42f/assignment-1/script.js#L73-L81

4. Naming variables are too generic. Names should be precise & accurately represent what they are for. 

https://github.com/ngxminhphuc/df-frontend-2023/blob/1eb943b12b6d76fb503de2b18e98d03dd83cd42f/assignment-1/script.js#L88
https://github.com/ngxminhphuc/df-frontend-2023/blob/1eb943b12b6d76fb503de2b18e98d03dd83cd42f/assignment-1/style.css#L46-L51
https://github.com/ngxminhphuc/df-frontend-2023/blob/1eb943b12b6d76fb503de2b18e98d03dd83cd42f/assignment-1/style.css#L109-L124

**Comment by ngxminhphuc** [comment]
Thank you very much and have a nice day!
